//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 05:03:10 AM GMT+03:00 
//


package ru.air.parser.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.air.parser.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.air.parser.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OnlineArrive }
     * 
     */
    public OnlineArrive createOnlineArrive() {
        return new OnlineArrive();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight }
     * 
     */
    public OnlineArrive.Flight createOnlineArriveFlight() {
        return new OnlineArrive.Flight();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight.Process }
     * 
     */
    public OnlineArrive.Flight.Process createOnlineArriveFlightProcess() {
        return new OnlineArrive.Flight.Process();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight.Route }
     * 
     */
    public OnlineArrive.Flight.Route createOnlineArriveFlightRoute() {
        return new OnlineArrive.Flight.Route();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight.Process.Baggage }
     * 
     */
    public OnlineArrive.Flight.Process.Baggage createOnlineArriveFlightProcessBaggage() {
        return new OnlineArrive.Flight.Process.Baggage();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight.Process.CheckIn }
     * 
     */
    public OnlineArrive.Flight.Process.CheckIn createOnlineArriveFlightProcessCheckIn() {
        return new OnlineArrive.Flight.Process.CheckIn();
    }

    /**
     * Create an instance of {@link OnlineArrive.Flight.Process.Boarding }
     * 
     */
    public OnlineArrive.Flight.Process.Boarding createOnlineArriveFlightProcessBoarding() {
        return new OnlineArrive.Flight.Process.Boarding();
    }

}
