//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 05:03:10 AM GMT+03:00 
//


package ru.air.parser.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flight" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="route">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="name_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="process">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="baggage">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="check-in" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dt_b" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="checkins" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="checkins_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="boarding" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="gate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="gate_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="rf_code" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="rf" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rf_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="flt" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="daname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="daname_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tws_arrive" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tws_arrive_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tws_depart" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tws_depart_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dp_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="dr_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="statuzz" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="statuzz_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="idirr" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="m2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="m2_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sovm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="sovm_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flight"
})
@XmlRootElement(name = "online_arrive")
public class OnlineArrive {

    protected List<OnlineArrive.Flight> flight;

    /**
     * Gets the value of the flight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnlineArrive.Flight }
     * 
     * 
     */
    public List<OnlineArrive.Flight> getFlight() {
        if (flight == null) {
            flight = new ArrayList<OnlineArrive.Flight>();
        }
        return this.flight;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="route">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="name_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="process">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="baggage">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="check-in" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dt_b" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="checkins" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="checkins_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="boarding" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="gate" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="gate_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="rf_code" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="rf" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rf_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="flt" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="daname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="daname_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tws_arrive" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tws_arrive_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tws_depart" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tws_depart_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dp" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dp_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="dr_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="statuzz" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="statuzz_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="idirr" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="m2" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="m2_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sovm" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sovm_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "route",
        "process"
    })
    public static class Flight {

        @XmlElement(required = true)
        protected OnlineArrive.Flight.Route route;
        @XmlElement(required = true)
        protected OnlineArrive.Flight.Process process;
        @XmlAttribute(name = "id")
        protected Integer id;
        @XmlAttribute(name = "rf_code")
        protected Short rfCode;
        @XmlAttribute(name = "rf")
        protected String rf;
        @XmlAttribute(name = "rf_eng")
        protected String rfEng;
        @XmlAttribute(name = "flt")
        protected Short flt;
        @XmlAttribute(name = "daname")
        protected String daname;
        @XmlAttribute(name = "daname_eng")
        protected String danameEng;
        @XmlAttribute(name = "tws_arrive")
        protected String twsArrive;
        @XmlAttribute(name = "tws_arrive_eng")
        protected String twsArriveEng;
        @XmlAttribute(name = "tws_depart")
        protected String twsDepart;
        @XmlAttribute(name = "tws_depart_eng")
        protected String twsDepartEng;
        @XmlAttribute(name = "dp")
        protected String dp;
        @XmlAttribute(name = "dp_eng")
        protected String dpEng;
        @XmlAttribute(name = "dr")
        protected String dr;
        @XmlAttribute(name = "dr_eng")
        protected String drEng;
        @XmlAttribute(name = "statuzz")
        protected String statuzz;
        @XmlAttribute(name = "statuzz_eng")
        protected String statuzzEng;
        @XmlAttribute(name = "idirr")
        protected Byte idirr;
        @XmlAttribute(name = "m2")
        protected String m2;
        @XmlAttribute(name = "m2_eng")
        protected String m2Eng;
        @XmlAttribute(name = "sovm")
        protected String sovm;
        @XmlAttribute(name = "sovm_eng")
        protected String sovmEng;

        /**
         * Gets the value of the route property.
         * 
         * @return
         *     possible object is
         *     {@link OnlineArrive.Flight.Route }
         *     
         */
        public OnlineArrive.Flight.Route getRoute() {
            return route;
        }

        /**
         * Sets the value of the route property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnlineArrive.Flight.Route }
         *     
         */
        public void setRoute(OnlineArrive.Flight.Route value) {
            this.route = value;
        }

        /**
         * Gets the value of the process property.
         * 
         * @return
         *     possible object is
         *     {@link OnlineArrive.Flight.Process }
         *     
         */
        public OnlineArrive.Flight.Process getProcess() {
            return process;
        }

        /**
         * Sets the value of the process property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnlineArrive.Flight.Process }
         *     
         */
        public void setProcess(OnlineArrive.Flight.Process value) {
            this.process = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the rfCode property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getRfCode() {
            return rfCode;
        }

        /**
         * Sets the value of the rfCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setRfCode(Short value) {
            this.rfCode = value;
        }

        /**
         * Gets the value of the rf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRf() {
            return rf;
        }

        /**
         * Sets the value of the rf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRf(String value) {
            this.rf = value;
        }

        /**
         * Gets the value of the rfEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRfEng() {
            return rfEng;
        }

        /**
         * Sets the value of the rfEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRfEng(String value) {
            this.rfEng = value;
        }

        /**
         * Gets the value of the flt property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getFlt() {
            return flt;
        }

        /**
         * Sets the value of the flt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setFlt(Short value) {
            this.flt = value;
        }

        /**
         * Gets the value of the daname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDaname() {
            return daname;
        }

        /**
         * Sets the value of the daname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDaname(String value) {
            this.daname = value;
        }

        /**
         * Gets the value of the danameEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDanameEng() {
            return danameEng;
        }

        /**
         * Sets the value of the danameEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDanameEng(String value) {
            this.danameEng = value;
        }

        /**
         * Gets the value of the twsArrive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTwsArrive() {
            return twsArrive;
        }

        /**
         * Sets the value of the twsArrive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTwsArrive(String value) {
            this.twsArrive = value;
        }

        /**
         * Gets the value of the twsArriveEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTwsArriveEng() {
            return twsArriveEng;
        }

        /**
         * Sets the value of the twsArriveEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTwsArriveEng(String value) {
            this.twsArriveEng = value;
        }

        /**
         * Gets the value of the twsDepart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTwsDepart() {
            return twsDepart;
        }

        /**
         * Sets the value of the twsDepart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTwsDepart(String value) {
            this.twsDepart = value;
        }

        /**
         * Gets the value of the twsDepartEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTwsDepartEng() {
            return twsDepartEng;
        }

        /**
         * Sets the value of the twsDepartEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTwsDepartEng(String value) {
            this.twsDepartEng = value;
        }

        /**
         * Gets the value of the dp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDp() {
            return dp;
        }

        /**
         * Sets the value of the dp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDp(String value) {
            this.dp = value;
        }

        /**
         * Gets the value of the dpEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDpEng() {
            return dpEng;
        }

        /**
         * Sets the value of the dpEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDpEng(String value) {
            this.dpEng = value;
        }

        /**
         * Gets the value of the dr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDr() {
            return dr;
        }

        /**
         * Sets the value of the dr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDr(String value) {
            this.dr = value;
        }

        /**
         * Gets the value of the drEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrEng() {
            return drEng;
        }

        /**
         * Sets the value of the drEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrEng(String value) {
            this.drEng = value;
        }

        /**
         * Gets the value of the statuzz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatuzz() {
            return statuzz;
        }

        /**
         * Sets the value of the statuzz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatuzz(String value) {
            this.statuzz = value;
        }

        /**
         * Gets the value of the statuzzEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatuzzEng() {
            return statuzzEng;
        }

        /**
         * Sets the value of the statuzzEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatuzzEng(String value) {
            this.statuzzEng = value;
        }

        /**
         * Gets the value of the idirr property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getIdirr() {
            return idirr;
        }

        /**
         * Sets the value of the idirr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setIdirr(Byte value) {
            this.idirr = value;
        }

        /**
         * Gets the value of the m2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getM2() {
            return m2;
        }

        /**
         * Sets the value of the m2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setM2(String value) {
            this.m2 = value;
        }

        /**
         * Gets the value of the m2Eng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getM2Eng() {
            return m2Eng;
        }

        /**
         * Sets the value of the m2Eng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setM2Eng(String value) {
            this.m2Eng = value;
        }

        /**
         * Gets the value of the sovm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSovm() {
            return sovm;
        }

        /**
         * Sets the value of the sovm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSovm(String value) {
            this.sovm = value;
        }

        /**
         * Gets the value of the sovmEng property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSovmEng() {
            return sovmEng;
        }

        /**
         * Sets the value of the sovmEng property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSovmEng(String value) {
            this.sovmEng = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="baggage">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="check-in" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dt_b" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="checkins" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="checkins_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="boarding" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="gate" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="gate_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "baggage",
            "checkIn",
            "boarding"
        })
        public static class Process {

            @XmlElement(required = true)
            protected OnlineArrive.Flight.Process.Baggage baggage;
            @XmlElement(name = "check-in")
            protected OnlineArrive.Flight.Process.CheckIn checkIn;
            protected OnlineArrive.Flight.Process.Boarding boarding;

            /**
             * Gets the value of the baggage property.
             * 
             * @return
             *     possible object is
             *     {@link OnlineArrive.Flight.Process.Baggage }
             *     
             */
            public OnlineArrive.Flight.Process.Baggage getBaggage() {
                return baggage;
            }

            /**
             * Sets the value of the baggage property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnlineArrive.Flight.Process.Baggage }
             *     
             */
            public void setBaggage(OnlineArrive.Flight.Process.Baggage value) {
                this.baggage = value;
            }

            /**
             * Gets the value of the checkIn property.
             * 
             * @return
             *     possible object is
             *     {@link OnlineArrive.Flight.Process.CheckIn }
             *     
             */
            public OnlineArrive.Flight.Process.CheckIn getCheckIn() {
                return checkIn;
            }

            /**
             * Sets the value of the checkIn property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnlineArrive.Flight.Process.CheckIn }
             *     
             */
            public void setCheckIn(OnlineArrive.Flight.Process.CheckIn value) {
                this.checkIn = value;
            }

            /**
             * Gets the value of the boarding property.
             * 
             * @return
             *     possible object is
             *     {@link OnlineArrive.Flight.Process.Boarding }
             *     
             */
            public OnlineArrive.Flight.Process.Boarding getBoarding() {
                return boarding;
            }

            /**
             * Sets the value of the boarding property.
             * 
             * @param value
             *     allowed object is
             *     {@link OnlineArrive.Flight.Process.Boarding }
             *     
             */
            public void setBoarding(OnlineArrive.Flight.Process.Boarding value) {
                this.boarding = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Baggage {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "status")
                protected String status;
                @XmlAttribute(name = "status_eng")
                protected String statusEng;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the statusEng property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatusEng() {
                    return statusEng;
                }

                /**
                 * Sets the value of the statusEng property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatusEng(String value) {
                    this.statusEng = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="gate" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="gate_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Boarding {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "status")
                protected String status;
                @XmlAttribute(name = "status_eng")
                protected String statusEng;
                @XmlAttribute(name = "dt_e")
                protected String dtE;
                @XmlAttribute(name = "gate")
                protected String gate;
                @XmlAttribute(name = "gate_eng")
                protected String gateEng;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the statusEng property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatusEng() {
                    return statusEng;
                }

                /**
                 * Sets the value of the statusEng property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatusEng(String value) {
                    this.statusEng = value;
                }

                /**
                 * Gets the value of the dtE property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDtE() {
                    return dtE;
                }

                /**
                 * Sets the value of the dtE property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDtE(String value) {
                    this.dtE = value;
                }

                /**
                 * Gets the value of the gate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGate() {
                    return gate;
                }

                /**
                 * Sets the value of the gate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGate(String value) {
                    this.gate = value;
                }

                /**
                 * Gets the value of the gateEng property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGateEng() {
                    return gateEng;
                }

                /**
                 * Sets the value of the gateEng property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGateEng(String value) {
                    this.gateEng = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dt_b" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="dt_e" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="checkins" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="checkins_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class CheckIn {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "status")
                protected String status;
                @XmlAttribute(name = "status_eng")
                protected String statusEng;
                @XmlAttribute(name = "dt_b")
                protected String dtB;
                @XmlAttribute(name = "dt_e")
                protected String dtE;
                @XmlAttribute(name = "checkins")
                protected String checkins;
                @XmlAttribute(name = "checkins_eng")
                protected String checkinsEng;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the status property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatus() {
                    return status;
                }

                /**
                 * Sets the value of the status property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatus(String value) {
                    this.status = value;
                }

                /**
                 * Gets the value of the statusEng property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStatusEng() {
                    return statusEng;
                }

                /**
                 * Sets the value of the statusEng property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStatusEng(String value) {
                    this.statusEng = value;
                }

                /**
                 * Gets the value of the dtB property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDtB() {
                    return dtB;
                }

                /**
                 * Sets the value of the dtB property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDtB(String value) {
                    this.dtB = value;
                }

                /**
                 * Gets the value of the dtE property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDtE() {
                    return dtE;
                }

                /**
                 * Sets the value of the dtE property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDtE(String value) {
                    this.dtE = value;
                }

                /**
                 * Gets the value of the checkins property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCheckins() {
                    return checkins;
                }

                /**
                 * Sets the value of the checkins property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCheckins(String value) {
                    this.checkins = value;
                }

                /**
                 * Gets the value of the checkinsEng property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCheckinsEng() {
                    return checkinsEng;
                }

                /**
                 * Sets the value of the checkinsEng property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCheckinsEng(String value) {
                    this.checkinsEng = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="status_eng" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Route {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "name_eng")
            protected String nameEng;
            @XmlAttribute(name = "status")
            protected String status;
            @XmlAttribute(name = "status_eng")
            protected String statusEng;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the nameEng property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNameEng() {
                return nameEng;
            }

            /**
             * Sets the value of the nameEng property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNameEng(String value) {
                this.nameEng = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the statusEng property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusEng() {
                return statusEng;
            }

            /**
             * Sets the value of the statusEng property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusEng(String value) {
                this.statusEng = value;
            }

        }

    }

}
